### ISSUE TITLE
Kemono API call failed

### ISSUE THREAD

**Issue by eyeszx** [Ljzd-PRO/KToolBox#104]
Any idea ?

![image_2024-05-04_201142382](https://github.com/Ljzd-PRO/KToolBox/assets/168929217/39ee612f-3449-486f-8e16-a85aaa9daf98)

**Comment by Ljzd-PRO** [comment]
It may caused by network issues

**Comment by ddt510** [comment]
I have encountered similar issue. coomer sometimes give me error 503. Does it mean the network issue is on the website's end?

.\ktoolbox sync-creator "https://coomer.su/onlyfans/user/hollyharper11" --start-time="2020-05-01" --end-time="2025-01-01"
2024-05-12 12:52:51.477 | INFO     | ktoolbox.cli:sync_creator:271 - Got creator information - {'name': 'hollyharper11', 'id': 'hollyharper11'}
2024-05-12 12:52:51.479 | INFO     | ktoolbox.action.job:create_job_from_creator:148 - Start fetching posts from creator hollyharper11
2024-05-12 12:52:56.477 | ERROR    | ktoolbox.api.base:_retry_error_callback:37 - Kemono API call failed - {'ret': APIRet(code=1002, message="1 validation error for Response\n  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\\n<html>\\...>\\n  </body>\\n</html>\\n', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.7/v/json_invalid", exception=1 validation error for Response
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/json_invalid, data=None)}
1 validation error for Response
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/json_invalid

**Comment by Ljzd-PRO** [comment]
> I have encountered similar issue. coomer sometimes give me error 503 while browsing it. Does it mean the network issue is on the website's end?
> 
> ```
> .\ktoolbox sync-creator "https://coomer.su/onlyfans/user/hollyharper11" --start-time="2020-05-01" --end-time="2025-01-01"
> 
> 2024-05-12 12:52:51.477 | INFO     | ktoolbox.cli:sync_creator:271 - Got creator information - {'name': 'hollyharper11', 'id': 'hollyharper11'}
> 2024-05-12 12:52:51.479 | INFO     | ktoolbox.action.job:create_job_from_creator:148 - Start fetching posts from creator hollyharper11
> 2024-05-12 12:52:56.477 | ERROR    | ktoolbox.api.base:_retry_error_callback:37 - Kemono API call failed - {'ret': APIRet(code=1002, message="1 validation error for Response\n  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\\n<html>\\...>\\n  </body>\\n</html>\\n', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.7/v/json_invalid", exception=1 validation error for Response
>   Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
>     For further information visit https://errors.pydantic.dev/2.7/v/json_invalid, data=None)}
> 1 validation error for Response
>   Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
>     For further information visit https://errors.pydantic.dev/2.7/v/json_invalid
> ```

```
PS C:\Users\mcdha\Downloads> ktoolbox sync-creator "https://coomer.su/onlyfans/user/hollyharper11" --start-time="2020-05-01" --end-time="2025-01-01"
2024-05-22 16:55:49.721 | INFO     | ktoolbox.cli:sync_creator:271 - Got creator information - {'name': 'hollyharper11', 'id': 'hollyharper11'}
2024-05-22 16:55:49.723 | INFO     | ktoolbox.action.job:create_job_from_creator:148 - Start fetching posts from creator hollyharper11
2024-05-22 16:55:51.686 | INFO     | ktoolbox.action.job:create_job_from_creator:174 - Get 140 posts, start creating jobs
1071779665_1080x1919_37ca7c4810a3393b5b4437b7265a51f4.jpg: 100%|████████████████████| 258k/258k [00:00<00:00, 359kiB/s]
1080x1920_b4666525d7888315f62c375493a06354.jpg: 100%|███████████████████████████████| 247k/247k [00:01<00:00, 134kiB/s]
1066830661_0hpnp137ua0agvbsn86uy_source.mp4:  25%|███████▊                       | 1.75M/6.97M [00:04<00:04, 1.30MiB/s]
```

I tried it and it works. If the Coomer API call fails, you can try modifying the configuration to:
```dotenv
# For Coomer API
KTOOLBOX_API__NETLOC=coomer.su

# For downloading files from Coomer server
KTOOLBOX_API__FILES_NETLOC=coomer.su
```

https://ktoolbox.readthedocs.io/latest/coomer/

**Comment by sHanbIgsUn** [comment]
> > I have encountered similar issue. coomer sometimes give me error 503 while browsing it. Does it mean the network issue is on the website's end?
> > ```
> > .\ktoolbox sync-creator "https://coomer.su/onlyfans/user/hollyharper11" --start-time="2020-05-01" --end-time="2025-01-01"
> > 
> > 2024-05-12 12:52:51.477 | INFO     | ktoolbox.cli:sync_creator:271 - Got creator information - {'name': 'hollyharper11', 'id': 'hollyharper11'}
> > 2024-05-12 12:52:51.479 | INFO     | ktoolbox.action.job:create_job_from_creator:148 - Start fetching posts from creator hollyharper11
> > 2024-05-12 12:52:56.477 | ERROR    | ktoolbox.api.base:_retry_error_callback:37 - Kemono API call failed - {'ret': APIRet(code=1002, message="1 validation error for Response\n  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\\n<html>\\...>\\n  </body>\\n</html>\\n', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.7/v/json_invalid", exception=1 validation error for Response
> >   Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
> >     For further information visit https://errors.pydantic.dev/2.7/v/json_invalid, data=None)}
> > 1 validation error for Response
> >   Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
> >     For further information visit https://errors.pydantic.dev/2.7/v/json_invalid
> > ```
> 
> ```
> PS C:\Users\mcdha\Downloads> ktoolbox sync-creator "https://coomer.su/onlyfans/user/hollyharper11" --start-time="2020-05-01" --end-time="2025-01-01"
> 2024-05-22 16:55:49.721 | INFO     | ktoolbox.cli:sync_creator:271 - Got creator information - {'name': 'hollyharper11', 'id': 'hollyharper11'}
> 2024-05-22 16:55:49.723 | INFO     | ktoolbox.action.job:create_job_from_creator:148 - Start fetching posts from creator hollyharper11
> 2024-05-22 16:55:51.686 | INFO     | ktoolbox.action.job:create_job_from_creator:174 - Get 140 posts, start creating jobs
> 1071779665_1080x1919_37ca7c4810a3393b5b4437b7265a51f4.jpg: 100%|████████████████████| 258k/258k [00:00<00:00, 359kiB/s]
> 1080x1920_b4666525d7888315f62c375493a06354.jpg: 100%|███████████████████████████████| 247k/247k [00:01<00:00, 134kiB/s]
> 1066830661_0hpnp137ua0agvbsn86uy_source.mp4:  25%|███████▊                       | 1.75M/6.97M [00:04<00:04, 1.30MiB/s]
> ```
> 
> I tried it and it works. If the Coomer API call fails, you can try modifying the configuration to:
> 
> ```dotenv
> # For Coomer API
> KTOOLBOX_API__NETLOC=coomer.su
> 
> # For downloading files from Coomer server
> KTOOLBOX_API__FILES_NETLOC=coomer.su
> ```
> 
> https://ktoolbox.readthedocs.io/latest/coomer/

请问为什么我打开VPN也会报楼主一样的错误，不开就下载速度特别慢，在100k以下

**Comment by Ljzd-PRO** [comment]
> 请问为什么我打开VPN也会报楼主一样的错误，不开就下载速度特别慢，在100k以下

如果用的是Clash的话，可以试一下开启服务模式和TUN模式，免去终端设置代理的步骤。

**Comment by sHanbIgsUn** [comment]
> > 请问为什么我打开VPN也会报楼主一样的错误，不开就下载速度特别慢，在100k以下
> 
> 如果用的是Clash的话，可以试一下开启服务模式和TUN模式，免去终端设置代理的步骤。

非常有效，感谢！另外我发现即使不使用VPN在凌晨两点到上午十点间也可以获得不错的下载速度

**Comment by Ljzd-PRO** [comment]
It is now understood that this may be due to frequent requests, so you can try setting a higher number of API retry attempts.

https://github.com/Ljzd-PRO/KToolBox/issues/113#issuecomment-2124227128
