### ISSUE TITLE
Can tasks be created solely based on the author's original name instead of their ID? 

### ISSUE THREAD

**Issue by rosechicken** [Ljzd-PRO/KToolBox#113]
Sometimes, if fetching the username fails, it defaults to using the ID for naming.

which might lead to redundant downloads if you're using "ktoolbox sync-creator" to retry downloading previously failed files, as the naming based on ID might differ. 

It's hoped to include a feature to retry reading the author's name when it fails, instead of using the ID for naming.

**Comment by Ljzd-PRO** [comment]
By default, all Kemono APIs will retry up to 3 times. You can modify this by setting `KTOOLBOX_API__RETRY_TIMES`.

```dotenv
# .env.prod
KTOOLBOX_API__RETRY_TIMES=10
```
