### ISSUE TITLE
Download only a type of attachment (zip)

### ISSUE THREAD

**Issue by shinkiro25** [Ljzd-PRO/KToolBox#118]
Is it possible to implement a filter to download only zip files from Kemono posts ?

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/KToolBox/issues/103#issuecomment-2094799100

**Comment by shinkiro25** [comment]
Does Ktoolbox automaticallhy import the .env instructions I add or do I have to add something else when running it in CMD ?

**Comment by Ljzd-PRO** [comment]
Currently, only reading `.env.prod` is not very reasonable. Support for `.env` will be added in the future.
