### ISSUE TITLE
附件文件名格式自定义的几个问题

### ISSUE THREAD

**Issue by WilliamBakersGithub** [Ljzd-PRO/KToolBox#128]
在使用SEQUENTIAL_FILENAME和FILENAME_FORMAT时遇到了几个问题：
首先，{}对应的文件名同时包含了文件名和扩展名，二者无法分开，导致想得到正常扩展名文件{}必须后置而无法在其他位置；
其次，一旦使用SEQUENTIAL_FILENAME后，附件原文件名便无法获取了，{}只能得到{序号}.{扩展名}。

我想将附件文件重命名为{序号}_{原文件名}.{扩展名}，但似乎没有办法可以实现。

希望原文件名、序号和文件扩展名都能加入到文件的属性当中，这样也能更方便对文件名进行自定义。

**Comment by Ljzd-PRO** [comment]
可以用 `{}_{title}` 命名。`title` 是整个作品的一个属性。
https://ktoolbox.readthedocs.io/latest/zh/configuration/reference/#ktoolbox.configuration.JobConfiguration

**Comment by WilliamBakersGithub** [comment]
> 可以用 `{}_{title}` 命名。`title` 是整个作品的一个属性。 https://ktoolbox.readthedocs.io/latest/zh/configuration/reference/#ktoolbox.configuration.JobConfiguration

{}_{title}得到的不是{序号}.{扩展名}_{Post名}吗，扩展名就没法后置，而且也拿不到附件文件的名字了

**Comment by Ljzd-PRO** [comment]
已经有试过了吗？或者 `{title}_{}` 这个我试过

**Comment by Ljzd-PRO** [comment]
附件文件名是没有。因为考虑到大多数作品里附件也就是图片，文件名都是哈希值。如果是通常数量比较少的那种“文件”的话，应该是不会按数字顺序命名的

**Comment by WilliamBakersGithub** [comment]
> 附件文件名是没有。因为考虑到大多数作品里附件也就是图片，文件名都是哈希值。如果是通常数量比较少的那种“文件”的话，应该是不会按数字顺序命名的
嗯包括{}_{title}基本所有命名的属性都试过了。附件名的话很多时候是既有直接贴上去的图片也有其它的压缩包和视频之类的附件一块的，这些的名字就一般有含义了，要是直接把名字覆盖成序号这些信息就丢失了，还会和图片混在一起，不用序号图片顺序又会乱，现在这样就很难两全。
之前用过一个叫Kemono-scraper的，那边作者就直接把序号加下划线前置到附件名前面，感觉那样更合适一些。
