### ISSUE TITLE
A sub-command to add post ID to left of folder's name would be helpful.

### ISSUE THREAD

**Issue by TheThirdComputer** [Ljzd-PRO/KToolBox#131]
A sub-command to add the post ID and other important variables to the left of the created folder's name would be really useful.

This would help with organizing folders by date with only a single click, and also not have to search trough several folders to find a specific post simply using an average search by ID or other variables. 
AND help avoid the issue of having several posts with the same name, thus the program creating a single folder putting content of different posts in the same folder, becoming confusing quickly.

Example:

https://kemono.su/patreon/user/26365500/post/91445419
Downloading this post from the artist named 'Heath Grace' with the command 'ktoolbox download-post' gives us a folder called = "Alex"
A more useful name could be = "91445419 Patreon Heath Grace = Alex"

Sorry if this is already possible, but if so, could someone explain me please?

**Comment by Ljzd-PRO** [comment]
https://ktoolbox.readthedocs.io/latest/configuration/guide/

use `KTOOLBOX_JOB__POST_DIRNAME_FORMAT`

```dotenv
KTOOLBOX_JOB__POST_DIRNAME_FORMAT=[{published}]{title}
```

**Comment by TheThirdComputer** [comment]
Ah, thank you, I forgot about checking the configuration tutorials. After some time researching, I managed to make them work.

**Comment by TheThirdComputer** [comment]
As a last reminder just in case anybody else also rather new, you have to create the file named 'prod.env' inside of the folder/directory where you are going to USE/WRITE YOUR COMMANDS, NOT inside of the directory of your KToolBox Phyton files.
