### ISSUE TITLE
Guide download from coomer

### ISSUE THREAD

**Issue by anabel79** [Ljzd-PRO/KToolBox#132]
May i ask how to download from coomer? i don't really understand how exactly .env work and where to put them? 
If no edit to .env it gives 0 posts
If i use .env edit it give this scfreenshort error

![Screenshot 2024-06-27 113901](https://github.com/Ljzd-PRO/KToolBox/assets/153075820/72ef2f76-8660-4286-b5af-3bf2de04a143)

a small tutorial will be helpful for me normies, thanks!

**Comment by Ljzd-PRO** [comment]
https://ktoolbox.readthedocs.io/latest/coomer/

The `prod.env` file should be placed in the working directory, which is the location where the command is executed.

**Comment by TheThirdComputer** [comment]
Put the 'prod.env' file in the directory/folder where you will execute the commands.

**Comment by tania0100** [comment]
> May i ask how to download from coomer? i don't really understand how exactly .env work and where to put them? If no edit to .env it gives 0 posts If i use .env edit it give this scfreenshort error
> 
> ![Screenshot 2024-06-27 113901](https://private-user-images.githubusercontent.com/153075820/343632830-72ef2f76-8660-4286-b5af-3bf2de04a143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzE4ODgsIm5iZiI6MTczNDk3MTU4OCwicGF0aCI6Ii8xNTMwNzU4MjAvMzQzNjMyODMwLTcyZWYyZjc2LTg2NjAtNDI4Ni1iNWFmLTNiZjJkZTA0YTE0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNjMzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTI4MmE4OTkzMmRhMmMxMzVlZDgzODFlOGU5NDdhMGUzMWYzODJjOTFmOGU0YmEwZWMwYWIzZjA2MjYzMjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6VtPsfSNNkh0g16V0A0wzx_m_sRBDJ534DaS3nFW6zw)
> 
> a small tutorial will be helpful for me normies, thanks!

if on linux.

in the folder that has your pyproject.toml
right click> create new document > empty document
rename the new file> "prod.env"
open prod.env in a text editor
paste lines from https://ktoolbox.readthedocs.io/latest/coomer/ in the newly opened .env document


save and close

**Comment by LuanaNight** [comment]
> The `prod.env` file should be placed in the working directory, which is the location where the command is executed.

Please add this detail to the docs, there is no way a non programmer would know this.
