### ISSUE TITLE
python的版本是必须为3.8吗 我安装了3.12版本的 使用pip3指令安装时候有报错

### ISSUE THREAD

**Issue by MuHei-del** [Ljzd-PRO/KToolBox#138]
![QQ图片20240718135204](https://github.com/user-attachments/assets/ef5c9560-613d-4cac-a418-1814d6732e1d)
第一次弄这种东西不太懂 麻烦大佬谅解一下

**Comment by Ljzd-PRO** [comment]
3.8-3.11都可以
