### ISSUE TITLE
如何自定义作者的名字？

### ISSUE THREAD

**Issue by axing0223** [Ljzd-PRO/KToolBox#145]
在作品文件与作品目录中可以分别使用
KTOOLBOX_JOB__FILENAME_FORMAT
KTOOLBOX_JOB__POST_DIRNAME_FORMAT
来修改作品与目录的名字。
那可以对作者的名字进行修改嘛？

**Comment by Ljzd-PRO** [comment]
不能，作者目录的话，可以考虑下载完以后手动更改目录名，毕竟就一个目录
