### ISSUE TITLE
Failed to fetch the name of creator

### ISSUE THREAD

**Issue by EIGHTfs** [Ljzd-PRO/KToolBox#151]
有时候网络不好获取不到作者名，软件会把 id 作为文件夹而不是作者名为文件夹，我希望的是获取不到作者名软件直接关闭，而不是继续下载。
因为有时候就变成了同一个作者下载了两遍（第一次获取到作者名了下载了一次，第二次想继续下载没获取作者名又下载一遍，，，）

**Comment by Ljzd-PRO** [comment]
现在获取不到名字会直接结束了。

**Comment by EIGHTfs** [comment]
> 现在获取不到名字会直接结束了。

用上了，好用
