### ISSUE TITLE
[BUG] Configuration 'retry_times' for downloads not working. Help?

### ISSUE THREAD

**Issue by TheThirdComputer** [Ljzd-PRO/KToolBox#152]
I'm using the prod.env file with the next line "KTOOLBOX_JOB__retry_times=2" in order to stop the amounts of retry for failed downloads from 10 to 2, but is not working.

Am I doing something wrong, or is there another problem? Help if possible, I'm not sure what else to try.

**Comment by Ljzd-PRO** [comment]
try `DOWNLOADER`
https://ktoolbox.readthedocs.io/latest/zh/configuration/reference/#ktoolbox.configuration.DownloaderConfiguration
```dotenv
KTOOLBOX_DOWNLOADER__RETRY_TIMES=2
```

**Comment by TheThirdComputer** [comment]
^ That works. Thanks.
