### ISSUE TITLE
content.txt

### ISSUE THREAD

**Issue by EIGHTfs** [Ljzd-PRO/KToolBox#162]
简单希望 content.txt 后缀换成 html，因为保持的内容确实也是 html 代码~~~~

**Comment by Ljzd-PRO** [comment]
之前其实是.html的😂但是看有些作品内容就只有普通文本，浏览器直接打开会有问题，所以后面又改成了txt

**Comment by Ljzd-PRO** [comment]
需要的话也可以自定义
```dotenv
# .env / prod.env
KTOOLBOX_JOB__POST_STRUCTURE__CONTENT_FILEPATH="content.html"
```
https://ktoolbox.readthedocs.io/latest/zh/configuration/reference/#ktoolbox.configuration.PostStructureConfiguration

**Comment by EIGHTfs** [comment]
> https://ktoolbox.readthedocs.io/latest/zh/configuration/reference/#ktoolbox.configuration.PostStructureConfiguration

好的
