### ISSUE TITLE
如何下载特定格式的档案

### ISSUE THREAD

**Issue by 1119387239** [Ljzd-PRO/KToolBox#172]
例如有时我只想下载图片 不想下载影片

查看文档后发现可以用allow_list指令来筛选

可是我不知道正确的完整指令该怎么打

我试过把allow_list=set(.jpg)加到prod.env里

可是没反应 希望可以讲解一下

**Comment by Ljzd-PRO** [comment]
可以试试
```dotenv
KTOOLBOX_JOB__ALLOW_LIST=["*.jpg"]
```

**Comment by Ljzd-PRO** [comment]
之后应该会做一个终端的图形界面，可以在里面创建和修改配置，这样会简单些

**Comment by Ljzd-PRO** [comment]
> 之后应该会做一个终端的图形界面，可以在里面创建和修改配置，这样会简单些

https://github.com/Ljzd-PRO/KToolBox/releases/tag/v0.10.0-beta.1

现在有了，不过可能测试的不够充分可能有问题

**Comment by 1119387239** [comment]
辛苦大佬了 马上去研究看看
