### ISSUE TITLE
能否通过更改设置对nekohouse.su网站的内容进行下载

### ISSUE THREAD

**Issue by EdwardRoyAdams** [Ljzd-PRO/KToolBox#210]
您好，我近日发现了网站nekohouse.su，此网站同kemono.su几乎完全相像，所以我尝试使用类似于在coomer.su下载文件的方法更改设置，并尝试在此网站进行下载，但程序无法下载并报错，由于我对编程和错误信息一窍不通，所以尝试将报错消息进行上传，如果您有空闲，麻烦您查看是否能够解决，非常感谢。
![Image_815093053076409](https://github.com/user-attachments/assets/e30db339-53aa-42d7-a945-5558a6454171)

**Comment by Ljzd-PRO** [comment]
看了一下这个网站似乎没有像kemono一样开放了API，例如kemono访问 `https://kemono.su/api/v1/posts` 是可以获取到近期作品的，但这个网站似乎不行，没有开放API的话，就没法用这个工具下载，应该只能爬虫。
