### ISSUE TITLE
希望能够添加按时间排序的下载功能  hope can add a descending chronological download feature 

### ISSUE THREAD

**Issue by Unnight** [Ljzd-PRO/KToolBox#28]
If i change the content of a creator's all posts download, it will be re-downloaded when i download the author again, so it will be difficult to re-edit it, but it would be great if you could download it In chronological order
It's a really great downloading tool
如果我下载某作者的全部内容后对内容进行更改，下一次下载该作者的文件时，那些更改过的文件会重新下载，这样想要对文件重新整理就会变得困难，如果未来能够添加选择时间段下载的功能，就更好了。
这是一个非常棒的下载工具

**Comment by Ljzd-PRO** [comment]
好的
