### ISSUE TITLE
rename attachment hash filename to number for reading with original order

### ISSUE THREAD

**Issue by Starlento** [Ljzd-PRO/KToolBox#33]
**Is your feature request related to a problem? Please describe.**

The attachment hash cannot match the original order when sorting by name.

**Describe the solution you'd like**

Add an argument to rename the filenames to 1.png ... x.png by original order.

**Describe alternatives you've considered**

Actually the post.json contains the dict with the right order. I am currently renaming the files by another python script. I am just asking whether it is easy to implement it in your code so that I can work on a PR. Or I can provide the code in this issue.

**Additional context**

**Comment by Starlento** [comment]
``` python
import json
import os

def get_attachment_dict(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data["attachments"]

folder = "xxx"
image_path = os.path.join(folder, "attachments")
attachment_list = get_attachment_dict(os.path.join(folder, "post.json"))

for i, attachment_info in enumerate(attachment_list):
    attachment_hash = attachment_info["name"]
    filename, extension = os.path.splitext(attachment_hash)
    os.rename(os.path.join(image_path, attachment_hash), os.path.join(image_path, str(i+1) + extension.lower()))
print(f"Finish renaming files for {folder}")
```

**Comment by Ljzd-PRO** [comment]
It is indeed necessary to add this feature.
