### ISSUE TITLE
kemono.su启用了DDoS防护

### ISSUE THREAD

**Issue by ADKYUSHU12321** [Ljzd-PRO/KToolBox#37]
**Is your feature request related to a problem? Please describe.**
kemono.su最近启用了DDoS防护，此程序的爬取速度过快容易触发规则
**Describe the solution you'd like**
能否增加一个慢速模式
**Describe alternatives you've considered**

**Additional context**

**Comment by Ljzd-PRO** [comment]
确实可以

**Comment by Ljzd-PRO** [comment]
不过一般都是在下载的时候不太顺利，把 `job.count` 设置为 `1` 应该会好些，这样就只会一个一个地下载。
```dotenv
KTOOLBOX_JOB__COUNT=10
```
https://ktoolbox.readthedocs.io/latest/zh/configuration/guide/

**Comment by kuugaoggy** [comment]
KTOOLBOX_JOB__ 之类的命令怎么用？显示一堆红字。我直接找目录下的configuration.py文件改的。

**Comment by Ljzd-PRO** [comment]
> KTOOLBOX_JOB__ 之类的命令怎么用？显示一堆红字。我直接找目录下的configuration.py文件改的。

这些配置要写入运行目录下的 `prod.env` 文件里。
https://ktoolbox.readthedocs.io/latest/zh/configuration/guide/
