### ISSUE TITLE
How to customize the format of the download directory?

### ISSUE THREAD

**Issue by clhs591027** [Ljzd-PRO/KToolBox#4]
Hello developer, I would like to ask how to customize the format of the download directory? The current default format is as follows:

..＼(creator name)＼(post name)＼attachments＼(file name).png

I want to change it to the following format:

..＼(creator ID)-(creator name)＼(post ID)-(post name)＼(post ID)-p001.png

thanks for your help!!

-----------------------------------------------------------------------

開發者你好, 想請教要如何自訂下載目錄的格式呢? 目前預設的格式如下:

..＼(作者名字)＼(作品名稱)＼attachments＼(檔案名稱).png

想改成以下格式:

..＼(作者ID)-(作者名字)＼(作品ID)-(作品名稱)＼(作品ID)-p001.png

感謝您的幫助!!

**Comment by Ljzd-PRO** [comment]
作者目录和作品目录的名字目前还改不了，作品目录的结构可以改。在工作目录下创建一个 `prod.env`，在里面写：
```dotenv
KTOOLBOX_JOB__POST_STRUCTURE__ATTACHMENTS=./
```
就可以了。这样作品目录下就不会多一个 `attachments`
对应的是：
https://github.com/Ljzd-PRO/KToolBox/blob/6c0978a7a59667ea1854df33947cf9b712a62344/ktoolbox/configuration.py#L56-L79
之后会有专门的说明
