### ISSUE TITLE
能不能在目录名录前加个贴子的发布时瘟

### ISSUE THREAD

**Issue by kuugaoggy** [Ljzd-PRO/KToolBox#45]
比如贴子名叫：サンタネモとかブーディカとか，想在前面加上[2023-12-28]

**Comment by Ljzd-PRO** [comment]
好的

**Comment by Ljzd-PRO** [comment]
作品目录命名格式加好了，不过还没有发布新版本。
可以在这里下载打包好的可执行文件：https://github.com/Ljzd-PRO/KToolBox/actions/runs/8308561667

需要设置配置，可以通过环境变量设置，或者运行目录下创建 `prod.env` 然后编辑
例如：
```dotenv
KTOOLBOX_JOB__POST_DIRNAME_FORMAT={published}{title}
```

具体用法：https://ktoolbox.readthedocs.io/devel/zh/configuration/reference/#ktoolbox.configuration.JobConfiguration

**Comment by Fkdxn** [comment]
> 加好了，不过还没有发布新版本。 可以在这里下载打包好的可执行文件：https://github.com/Ljzd-PRO/KToolBox/actions/runs/8308561667
> 
> 需要设置配置，可以通过环境变量设置，或者运行目录下创建 然后编辑 例如：`prod.env`
> 
> ```dotenv
> KTOOLBOX_JOB__POST_DIRNAME_FORMAT={published}{title}
> ```
> 
> 具体用法：https://ktoolbox.readthedocs.io/devel/zh/configuration/reference/#ktoolbox.configuration.JobConfiguration



> ```dotenv
> KTOOLBOX_JOB__POST_DIRNAME_FORMAT={published}{title}
> ```
可以的，完美解决同一文件夹名称会覆盖内部文件的问题，有些作者喜欢一个名字干到底哈哈哈，我设置的{title}_{id}，应该不会重复了
![QQ截图20240323163636](https://github.com/Ljzd-PRO/KToolBox/assets/146941702/9b3c227a-0849-4456-b1be-033dbcf8eac6)
![QQ截图20240323170755](https://github.com/Ljzd-PRO/KToolBox/assets/146941702/8d593549-f3df-4c0c-984a-355a482a0d32)
