### ISSUE TITLE
请求添加重命名附件时指定或排除文件类型的功能

### ISSUE THREAD

**Issue by colinpyy** [Ljzd-PRO/KToolBox#46]
请求添加按照数字顺序重命名附件时指定或排除特定文件类型的功能。
最好可以使用例如"{date}_{titel}_{index}.{ext}"的格式自定义文件重命名格式。
文件夹命名也可以像这样支持自定义修改格式如添加日期和其他信息就好了。

**Comment by Ljzd-PRO** [comment]
好的

**Comment by Ljzd-PRO** [comment]
作品目录命名格式加好了，不过还没有发布新版本。
可以在这里下载打包好的可执行文件：https://github.com/Ljzd-PRO/KToolBox/actions/runs/8308561667

需要设置配置，可以通过环境变量设置，或者运行目录下创建 `prod.env` 然后编辑
例如：
```dotenv
KTOOLBOX_JOB__POST_DIRNAME_FORMAT={published}{title}
```

具体用法：https://ktoolbox.readthedocs.io/devel/zh/configuration/reference/#ktoolbox.configuration.JobConfiguration
