### ISSUE TITLE
同时下载两个同名不同后缀的文件会失败

### ISSUE THREAD

**Issue by colinpyy** [Ljzd-PRO/KToolBox#47]
当我下载的同一个帖子中有一对同名的psd和clip文件时，先下载到达100%的文件总是会出错
`Download failed - {'filename': 'Reward 2023-09-17.clip', 'exception': PermissionError(13, '另一个程序正在使用此文件，进程无法访问。')}`
猜测应该时使用相同的tmp作为临时后缀名导致的

**Comment by Fkdxn** [comment]
我今天也发现了，两个同名不同后缀的文件tongshi同时下载只会生成一个.tmp文件，然后任意一个下载完成就会冲突报错，目前在prod.ENV里设置了单个下载，等一个修复吧
![QQ截图20240225144536](https://github.com/Ljzd-PRO/KToolBox/assets/146941702/332221ef-7308-49ee-ac34-2a36d57cf89c)
![QQ截图20240225144629](https://github.com/Ljzd-PRO/KToolBox/assets/146941702/b916a0a7-6127-4c8a-9c56-7cec2b1bf0ea)
