### ISSUE TITLE
'ktoolbox' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by fateyoujo** [Ljzd-PRO/KToolBox#58]
python3.11.8安装后,命令无法识别

![{C9E0482C-FC84-4670-934C-135DA2118652}](https://github.com/Ljzd-PRO/KToolBox/assets/115338760/6fbff45a-edd2-4488-a5df-c72790b3c50d)
![屏幕截图 2024-02-13 213622](https://github.com/Ljzd-PRO/KToolBox/assets/115338760/8f8d1e7a-1ebb-46f1-b9e8-a1a06bd2361a)

exe文件只会闪退
![屏幕截图 2024-02-13 214753](https://github.com/Ljzd-PRO/KToolBox/assets/115338760/96d1d167-2f38-4660-9b76-651fefbd2489)

**Comment by Ljzd-PRO** [comment]
如果是手动用python运行的话，python安装以后还要用包管理器安装ktoolbox，推荐用pipx。先用自带的pip（如果没有的话可以网上查一下配置方法），`pip install pipx`，然后用 pipx 安装 ktoolbox，`pipx install ktoolbox`。pip和pipx差别是pip会默认把包安装到全局的环境下，pipx安装这些应用程序会自动进行环境隔离。

**Comment by Ljzd-PRO** [comment]
> exe文件闪退是因为直接运行的话会输出帮助信息，之后程序就结束了，windows终端窗口就会自动关闭。可以按住 Shift 键然后在当前目录打开终端，然后就可以使用命令了

ktoolbox.exe 相当于就是命令开头的 ktoolbox。比如 `ktoolbox.exe -h`，`.\ktoolbox.exe -h` 都是可以的，或者就直接 `ktoolbox -h`

**Comment by Ljzd-PRO** [comment]
> 如果是手动用python运行的话，python安装以后还要用包管理器安装ktoolbox，推荐用pipx。先用自带的pip（如果没有的话可以网上查一下配置方法），`pip install pipx`，然后用 pipx 安装 ktoolbox，`pipx install ktoolbox`。pip和pipx差别是pip会默认把包安装到全局的环境下，pipx安装这些应用程序会自动进行环境隔离。

这里命令无法被识别的原因应该是和环境变量设置有关，用pipx的话就省事的多

**Comment by fateyoujo** [comment]
> exe文件闪退是因为直接运行的话会输出帮助信息，之后程序就结束了，windows终端窗口就会自动关闭。可以按住 Shift 键然后在当前目录打开终端，然后就可以使用命令了

多谢佬的回复，比教程文件有用多了，一下就说出问题在哪里(›´ω`‹ )

**Comment by Ljzd-PRO** [comment]
```powershell
python -m pipx ensurepath
```

试试看能不能自动设置好环境变量。

或者用系统层级的包管理工具安装pipx

```powershell
scoop install pipx
```

参考 https://github.com/pypa/pipx#on-windows

命令还是识别不到是因为python安装的包和可执行文件都在用户目录下的.local目录里，Unix是这样的，Windows应该差不多，但这个目录一般没有被添加到环境变量

**Comment by fateyoujo** [comment]
> ```powershell
> python -m pipx ensurepath
> ```
> 
> 试试看能不能自动设置好环境变量。
> 
> 或者用系统层级的包管理工具安装pipx
> 
> ```powershell
> scoop install pipx
> ```
> 
> 参考 https://github.com/pypa/pipx#on-windows
> 
> 命令还是识别不到是因为python安装的包和可执行文件都在用户目录下的.local目录里，Unix是这样的，Windows应该差不多，但这个目录一般没有被添加到环境变量


折腾了五个小时python，终于解决问题了。

在五个小时不断的重装之中，
摸透了各种环境变量的精髓。

最后发现影响安装的坏东西，

是过去的卸载残留，导致重装期间，连pip都一直报错，

把appdata的python删除干净，重装就能出现正常的warning，
听它的话，老老实实添加变量，
![屏幕截图 2024-02-14 222705](https://github.com/Ljzd-PRO/KToolBox/assets/115338760/74ccd9e1-8b28-4c09-9967-563bb5a9ee83)



然后问题也就稀里糊涂的解决了∠( ᐛ 」∠)＿
