### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by C60000** [Ljzd-PRO/KToolBox#59]
问题：
第一次下载时正常，但进行到一半出现错误无法继续，之后的下载不论将同时下载作品数调成多少，都只会显示：

20xx-xx-xx xx:xx:xx.xxx | ERROR    | ktoolbox.api.base:_retry_error_callback:37 - Kemono API call failed - {'ret': APIRet(code=1001, message='', exception=ConnectError(''), data=None)}

![屏幕截图 2024-02-18 173206](https://github.com/Ljzd-PRO/KToolBox/assets/86367932/0b52b3c4-a7d2-4766-8e26-fb82fb749dc2)

**Comment by C60000** [comment]
重装KtoolBox后依旧无法下载

**Comment by Ljzd-PRO** [comment]
看上去是网络问题，也可能是触发风控了，我试了多文件/图片的作品是可以下载的

**Comment by C60000** [comment]
不太像是网络问题……？
手动下载（原始下载方式）目前正常

如果是触发风控（同时下载数我已经改成1了），有解决方案吗

**Comment by Ljzd-PRO** [comment]
一般就算风控也不会一直访问失败，这连接失败看上去是连接服务器都失败了，可以试试使用网络代理。（系统设置里设置的代理不会应用到终端程序，一般来说代理软件会提供终端设置代理的命令，复制粘贴回车就可以设置好代理，或者就通过别的方式，类似游戏加速器那种会创建一个虚拟网卡的）

**Comment by Fkdxn** [comment]
上午还好好的，晚上也出现这种了：

**Comment by Fkdxn** [comment]
2024-02-25 21:05:41.184 | ERROR    | ktoolbox.api.base:_retry_error_callback:37 - Kemono API call failed - {'ret': APIRet(code=1002, message="1 validation error for Response\n  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\\n<html>\\...>\\n  </body>\\n</html>\\n', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid", exception=1 validation error for Response
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid, data=None)}
1 validation error for Response
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value='<!DOCTYPE html>\n<html>\...>\n  </body>\n</html>\n', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/json_invalid

**Comment by Ljzd-PRO** [comment]
可能是服务器出问题了，刚才我浏览器直接访问kemono.su，结果是502

**Comment by Ljzd-PRO** [comment]
> 可能是服务器出问题了，刚才我浏览器直接访问kemono.su，结果是502

coomer.su 也是

**Comment by Fkdxn** [comment]
> 可能是服务器出问题了，刚才我浏览器直接访问 kemono.su，结果是502

今早测试又可以了，估计就是服务器抽风了 哈哈 大佬做的这个真nb，对了大佬那个同名文件同时下载会冲突的情况有计划修复吗？不然这类资源得单线程下，辛苦了

**Comment by Ljzd-PRO** [comment]
> > 可能是服务器出问题了，刚才我浏览器直接访问 kemono.su，结果是502
> 
> 今早测试又可以了，估计就是服务器抽风了 哈哈 大佬做的这个真nb，对了大佬那个同名文件同时下载会冲突的情况有计划修复吗？不然这类资源得单线程下，辛苦了

修复了，不过还没有发布新版本😂
可以先用自动构建的：https://github.com/Ljzd-PRO/KToolBox/actions/runs/8041352356

**Comment by Fkdxn** [comment]
> > > 可能是服务器出问题了，刚才我浏览器直接访问 kemono.su，结果是502
> > 
> > 
> > 今早测试又可以了，估计就是服务器抽风了 哈哈 大佬做的这个真nb，对了大佬那个同名文件同时下载会冲突的情况有计划修复吗？不然这类资源得单线程下，辛苦了
> 
> 修复了，不过还没有发布新版本😂 可以先用自动构建的：https://github.com/Ljzd-PRO/KToolBox/actions/runs/8041352356

完美！
![QQ截图20240228145958](https://github.com/Ljzd-PRO/KToolBox/assets/146941702/992a0232-f62b-4c8b-ae5f-e67162522671)
