### ISSUE TITLE
[ PR Feature ] 使用桶存储模式保存所有数据

### ISSUE THREAD

**Issue by Nacosia** [Ljzd-PRO/KToolBox#74]
有时候下载会把以前下载好的移除, 或是当文件名重复时`ktoolbox`会拒绝下载它. 我不想失去任何数据. 是否考虑使用桶存储方式不冲突的保留数据.
我使用 `hard link` 实现了它, 但是我的 python 并不算精通. 所以想请问一下是否可以提交PR, 因为我无法保障在我不熟悉的领域它是否有隐藏缺陷.
https://github.com/Nacosia/KToolBox/commit/6450b66ef5dcfc8efd242a9ac6d69e1cbb7b75a1

另外, 我有一个迁移脚本, 可以将以前的数据迁移为此模式.

**Comment by Ljzd-PRO** [comment]
合并了，不过修改了一些地方，可以试试能否正常使用

**Comment by Nacosia** [comment]
感谢您的修改, 很抱歉没有注意到此消息. 经过一些小的测试, 它的工作是正常的!

**Comment by Ljzd-PRO** [comment]
好的
