### ISSUE TITLE
系统找不到指定的路径

### ISSUE THREAD

**Issue by pieceofsht** [Ljzd-PRO/KToolBox#94]
![{95AE7F3F-52BD-43bc-B2B3-6922DAC00499}](https://github.com/Ljzd-PRO/KToolBox/assets/109125142/df2874f5-02fd-464d-bdc3-e6e7a45b76e4)
是不是文件名里的“/”没用正则表达式换掉啊

**Comment by Ljzd-PRO** [comment]
应该是
